config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers, except: [:index]

  resources :transactions
  post 'checkout', to: 'transactions#checkout'

  get 'search', to: 'offers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord

  include PgSearch::Model

  belongs_to :user
  has_many :transactions

  validates :address, :price, :description, :capacity, :title, :photo, presence: true

  def offer_address
    [city, state].compact.join(', ')
  end

  # def self.search(location)
  #   if location
  #     Offer.where('address ILIKE ?', "%#{location}%")
  #   else
  #     []
  #   end
  pg_search_scope :search_by_title_city_state_address_and_description,
    against: [ :title, :city, :state, :description, :address ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :offers
  has_many :transactions

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, except: [:index]


  def index
    if params[:query].present?
      @offers = policy_scope(Offer).search_by_title_city_state_address_and_description(params[:query]).order(created_at: :desc)
    else
      @offers = policy_scope(Offer).order(created_at: :desc)
    end
  end

  def new
    # @offer = current_user.offers.build
    @offer = Offer.new
    authorize @offer
    # return true
  end

  def create
    @offer = current_user.offers.build(offer_params)
    authorize @offer
    if @offer.save
      flash[:notice] = "Your offer was successfully created"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    authorize @offer
  end

  def edit
    authorize @offer
  end

  def update
    authorize @offer
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'Offer was successfully updated.'
    else
      render :edit
    end
  end

  # def edit
  #   if current_user.id != @offer.user.id
  #     redirect_to root_path
  #     flash[:alert] = "You don't have permission"
  #   end
  # end

  def destroy
    authorize @offer
    @offer.destroy
    flash[:notice] = "Your offer was removed successfully"
    redirect_to offers_path
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params[:offer] ||= []
    params.require(:offer).permit(
      :address, :capacity,
      :city, :description,
      :state,
      :title, :price, :photo
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def search
    @address = params[:address]
    @state = params[:state]
    @home_type = params[:home_type]
    @city = params[:city]
    @checkin = params[:checkin]
    @checkout = params[:checkout]
    @guests = params[:guests] || 1
    # @stays = Offer.search(@city)
    # if @stays.blank?
     #  @offers = Offers.all
end

end



  #skip_before_action :authenticate_user!, only: :home
  # def home
  # end

  # def dashboard
    # pegar todas reservas onde user id = user id atual
    # criar rota para esse metodo
    # @bookings = Booking.where(user_id: current_user).order(:start_date)
# end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = current_user.reservation.all
  end

  def new
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @transaction = current_user.transactions.build(transaction_params)
    @nights = params[:nights]
    if @transaction.save
      render 'payment'
    else
      flash[:alert] = "Something went wrong"
      redirect_to offer_path(@offer)
    end
  end

  def payment
  end

  def checkout
    @offer = Offer.find(params[:offer_id])
    @transaction = @offer.transactions.find(params[:transaction_id]);
    begin
      @amount = params[:price]
      user = Stripe::User.create({
        email: current_user.email,
        source: params[:stripeToken],
      })

      charge = Stripe::Charge.create({
        user: user.id,
        amount: @amount.to_i,
        description: 'AirBnB customer',
        currency: 'BRL',
      })
    rescue Stripe::CardError => e
      charge_error = e.message
    end

    if charge_error
      @transaction.destroy
      flash[:alert] = charge_error
      redirect_to offer_path(@offer)
    else
      flash[:notice] = "Your place was booked!"
      redirect_to trips_path
    end
  end

  def destroy
    @offer = Offer.find(params[:offer_id])
    @transaction = @offer.transactions.find(params[:id])
    @transaction.destroy
    flash[:alert] = "Your booking was cancelled"
    redirect_to trips_path
  end

  private

  def transaction_params
    params.require(:transaction).permit(:start_date, :end_date, :price, :total, :offer_id, :nights)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<div id="form">
  <%= form_for(@offer) do |f| %>
    <div class="columns mt-4 is-mobile change-mobile">
      <div class="column is-two-fifths-mobile is-one-third-desktop is-one-third-widescreen change-column" style="width:auto !important;">
        <div class="field">
          <label class="label">Offer</label>
          <div class="control">
            <div class="select">
              <%= f.select(:home_type, options_for_select([["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]])) %>
            </div>
          </div>
        </div>
      </div>
      <
      <div class="column is-two-fifths-mobile is-one-third-desktop is-one-third-widescreen change-column">
        <div class="field">
          <label class="label">How many guests</label>
          <div class="control">
            <div class="select">
              <%= f.select(:capacity, options_for_select([["for 1 guest", 1], ["for 2 guests", 2], ["for 3 guests", 3], ["for 4 guests", 4], ["for 5 guests", 5], ["for 6 guests", 6]])) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="columns mt-3 is-mobile change-mobile">
      <div class="column">
        <div class="field">
          <label class="label">Offer Title</label>
          <div class="control">
            <%= f.text_field :title, class: "input", placeholder: "Be clear and descriptive" %>
          </div>
        </div>
      </div>
    </div>

    <div class="columns mt-3 is-mobile change-mobile">
      <div class="column is-half-widescreen is-half-desktop">
        <div class="field">
          <label class="label">City</label>
          <div class="control">
            <%= f.text_field :city, class: "input", placeholder: "Enter your city" %>
          </div>
        </div>
      </div>
      <div class="column is-half-widescreen is-half-desktop">
        <div class="field">
          <label class="label">State</label>
          <div class="control">
            <%= f.text_field :state, class: "input", placeholder: "Enter your state" %>
          </div>
        </div>
      </div>
    </div>
    <div class="columns mt-3 is-mobile change-mobile">
      <div class="column">
        <div class="field">
          <label class="label">Address</label>
          <div class="control">
            <%= f.text_field :address, class: "input", placeholder: "What is your address?" %>
          </div>
        </div>
      </div>
    </div>
    <div class="columns mt-3 is-mobile change-mobile">
      <div class="column">
        <div class="field">
          <label class="label">Price</label>
          <div class="control has-icons-left">
            <%= f.text_field :price, class: "input", placeholder: "xxxx" %>
            <span class="icon is-left"><i class="fa fa-rupee", style="color: rgb(23, 23, 23);"></i></span>
          </div>
        </div>
      </div>
    </div>
    <div class="columns mt-3 is-mobile change-mobile">
      <div class="column">
        <div class="field">
          <label class="label">Add Images<span style="color: #ff5b5b; font-size: 0.8rem;"> (Add atleast 5 images)</span></label>
          <div class="control">
            <input placeholder="Url 1" type="text" name="offer[urls][]" class="input">
            <input placeholder="Url 2" type="text" name="offer[urls][]" class="input">
            <input placeholder="Url 3" type="text" name="offer[urls][]" class="input">
            <input placeholder="Url 4" type="text" name="offer[urls][]" class="input">
            <input placeholder="Url 5" type="text" name="offer[urls][]" class="input">
          </div>
        </div>
      </div>
    </div>
    <%= render 'images' %>
    <%= f.submit @offer.persisted? ? "Update your offer" : "Create your offer", class: "button is-dark mt-5 chng" %>
  <% end %>
</div>

app/views/offers/edit.html.erb
<div class="columns is-mobile">
  <div class="column is-three-fifths-mobile is-two-thirds-desktop is-three-fifths-widescreen">
    <div class="wrap mb-5">
     <h1 class="is-size-2"> Edit your Offer</h1>
      <%= render 'form' %>
    </div>
  </div>
  <div class="column image">
    <%= image_tag 'image4.png', style: "float:right; height: 100%;"%>
  </div>
</div>

app/views/offers/index.html.erb
<div class="container d-flex justify-content-around">
  <div class="col-8">
    <% @offers.each do |offer| %>
      <%= link_to offer_path(offer) do %>
        <div class="card-trip mb-5">
          <%= image_tag offer.photo %>
          <div class="card-trip-infos">
            <div>
              <h2><%= offer.title %></h2>
              <p><%= offer.description %></p>
            </div>
            <h1 class="card-trip-user">R$<%= offer.price %></h1>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/offers/index1.html.erb
<div class="wrapper">
  <div class="container is-fluid">
    <h1 class="is-size-1 has-text-centered has-text-weight-semibold mb-6">Your Offers</h1>
    <% if @offers.any? %>
      <% @offers.each do |offer| %>
        <article class="media">

          <div class="media-content">
            <span class="is-size-5"><%= offer.state %> in <%= offer.city %></span>
            <h3 class="is-size-3 has-text-weight-semibold"><%= link_to offer.title, offer_path(offer), class: "offerlink" %></h3>
            <hr>
            <ul class="ul">
              <li><%= pluralize(offer.capacity, ' guest') %></li>

            </ul>
            <h2 class="is-size-5 mt-4"><strong><i class="fa fa-rupee mr-1"></i><%= offer.price %></strong> / night</h2>
            <div class="field is-grouped" style="margin-top: 14vh;">
              <p class="control">
                <%= link_to "Update your space", edit_offer_path(offer), class:"button is-small has-text-weight-semibold" %>
              </p>
              <p class="control">
                <%= link_to "Remove your space", offer_path(offer), method: :delete, data: {confirm: "Are you sure?"}, class:"button is-warning is-small has-text-weight-semibold" %>
              </p>
            </div>
          </div>
        </article>
        <hr style="margin: 2vh 0 !important;">
      <% end %>
    <% else %>
      <div class="nothing" style="margin-bottom: 28vh; margin-top: 20vh;">
        <h1 style="font-size:2.5rem; text-align:center;">You have no space listed, go on</h1>
        <%= link_to "List your space", new_offer_path, class:"button is-link mt-5 listspacebtn", style: "left: 45%"%>
      </div>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="total-offer-new">
  <h2 class="text-center my-5 text-danger">Share your <strong id="red-word">House or Apartment</strong>.</h2>

  <div class="container container-person">
    <div id="wrapper">
      <div class="row">
        <div class="text-left form-login">
          <br>
          <%= simple_form_for @offer do |f| %>
          <%= f.error_notification %>
          <%= f.input :title, label: "Title", placeholder: "Studio Apartment Downtown" %>
          <%= f.input :description, placeholder: "King size bed, large living room...", :label_html => { :class => "label-css"} %>
          <%= f.input :address, label: "My House or Apartment is located at this address", placeholder: "Avenida Paulista 123" %>
          <div class="d-flex justify-content-center">
            <%= f.input :city, placeholder: "São Paulo", input_html: { class: "mr-4" } %>
            <%= f.input :state, priority: ["SP"], input_html: { value: "SP", disabled: true } %>
          </div>
          <%= f.input :photo, label: "Photo of the property", placeholder: "URL photo" %>
          <div class="d-flex justify-content-center">
            <%= f.input :capacity, label: "Capacity" %>
            <%= f.input :price, label: "Price per night in BRL", placeholder: "150" %>
          </div>
          <div class="d-flex justify-content-center">
            <%= f.button :submit, "Share my House/Apartment", class: "btn-submit-offer"%>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="wrapper">
  <div class="container is-fluid space">
    <h5 class="is-size-5 mb-4"><%= link_to "Back to list", offers_path %></h5>
    <h1 class="is-size-2 has-text-weight-semibold"><%= @offer.title %></h1>
    <h2 class="is-size-2 has-text-weight-semibold"><%= "R$#{@offer.price},00/night" %></h2>
    <h4 class="is-size-5 mb-4" style="text-decoration: underline;"><%= "#{@offer.city}, #{@offer.state}" %></h4>
    <div class="offer-images">

    </div>
    <div class="columns is-mobile mt-5 desc-column">
      <div class="column is-two-thirds-widescreen is-full-desktop is-full-mobile">
        <h2 class="is-size-3 has-text-weight-semibold" style="display: inline-block !important;">
          <%= @offer.city.capitalize %> Hosted by <%= @offer.user.email.split('@')[0] %>
        </h2>
        <span class="avatar"><img src="https://img.icons8.com/bubbles/80/000000/user-male.png"/></span>
        <ul class="ul" style="margin-bottom: 4vh !important;">
          <li><%= pluralize(@offer.capacity, ' guest') %></li>

        </ul>
        <hr>
        <p class="description mb-3">
          <%= @offer.description %>
        </p>

        <h4 class="mt-4 mb-5">
          <span class="has-text-weight-semibold continue_google" id="readlink">More info contact the owner via email</span><span style="font-size: 17px !important;">: <%= current_user.email %></span>
        </h4>
        <hr>


    </div>
    <div class="card mapcard">
      <div id="mapp">
      </div>
    </div>
  </div>
</div>

app/views/pages/_footer.html.erb
<footer class="footer" style="padding: 2rem 1.5rem;background-color: #f0f0f0;">
  <div class="columns">
    <div class="column tab">
      <p>&copy; MelhorAjuda Team</p>
      <ul class="mt-2">
        <li><a href="#" class="link">Privacy</a></li>
        <li><a href="#" class="link">Terms</a></li>
        <li><a href="https://www.github.com/lexsimoes" class="link">About</a></li>
      </ul>
    </div>
    <div class="column tabtwo">
      <p class="buttons">
        <button class="button" style="border-radius: 25px">
          <span class="icon is-large">
            <i class="fa fa-facebook-f"></i>
          </span>
        </button>
        <button class="button" style="border-radius: 25px">
          <span class="icon">
            <i class="fa fa-github"></i>
          </span>
        </button>
        <button class="button" style="border-radius: 25px">
          <span class="icon">
            <i class="fa fa-instagram"></i>
          </span>
        </button>
      </p>
    </div>
  </div>
</footer>

app/views/pages/_navbar.html.erb
<nav class="navbar is-fixed-top is-flex is-justify-content-space-between is-align-items-center" id="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <%= image_tag("airrbnb.png", class: "img") %>
      <h1 class="brand ml-1">Le AirBnB</h1>
    <% end %>
  </div>

  <div>
    <button class="locationBtn button is-rounded">
      <span class="icon has-text-info">
        <i id="icon" class="fa fa-search icon"></i>
      </span>
      <h4>
        <%= link_to "Find a location", root_path, class: "location", style: "color:black;" %>
      </h4>
    </button>
  </div>

  <div class="buttons">
    <% if !user_signed_in? %>
      <strong><%= link_to "Sign Up", new_user_registration_path, class: "button is-rounded mr-3" %></strong>
      <strong><%= link_to "Log in", new_user_session_path, class: "button is-rounded" %></strong>
  </div>
  <% else %>
    <div class="dropdown is-right">
      <div class="dropdown-trigger">
        <button class="button dropBtn" style="transition: 0.2s;" aria-haspopup="true" aria-controls="dropdown-menu">
          <span class="icon">
            <img src="https://img.icons8.com/android/15/000000/menu.png", class="mr-3"/>
            <img src="https://img.icons8.com/ios-filled/50/000000/user-male-circle.png"/>
          </span>
        </button>
      </div>
      <div class="dropdown-menu" id="dropdown-menu" role="menu">
        <div class="dropdown-content">
          <%= link_to "Trips", trips_path, class:"dropdown-item" %>
          <%= link_to "Host your home", new_room_path, class:"dropdown-item" %>
          <%= link_to "Your listings", rooms_path, class:"dropdown-item" %>
          <%= link_to "Account", edit_user_registration_path(@user), class:"dropdown-item" %>
          <hr class="dropdown-divider">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    </div>
    <script>
      const dropdownTrigger = document.querySelector('.dropBtn');
      const dropdownMenu = document.querySelector('.dropdown');
      $('body').on('click', (e) => {
        if(e.target.closest('.dropdown') !== dropdownMenu && dropdownMenu.classList.contains('is-active')) {
          dropdownMenu.classList.remove('is-active');
        }
      });
      dropdownTrigger.addEventListener('click', () => {
        if(!dropdownMenu.classList.contains('is-active')){
          dropdownMenu.classList.add('is-active');
        } else{
          dropdownMenu.classList.remove('is-active');
        }
      });
    </script>
  <% end %>
</nav>
<nav class="navbar is-fixed-bottom" id="bottom-navbar" role="navigation" aria-label="main navigation">
  <% if !user_signed_in? %>
    <div class="columns is-mobile mt-1">
      <div class="column is-offset-1">
        <%= link_to root_path, class: "items" do %>
          <img src="https://img.icons8.com/color/40/000000/airbnb.png"/>
          <span style="display:block;">Explore</span>
        <% end %>
      </div>
      <div class="column">
        <%= link_to new_user_registration_path, class: "items" do %>
          <img src="https://img.icons8.com/ios/40/000000/send-letter--v1.png"/>
          <span style="display:block;">Sign Up</span>
        <% end %>
      </div>
      <div class="column">
        <%= link_to new_user_session_path, class: "items" do %>
          <img src="https://img.icons8.com/carbon-copy/40/000000/user-male-circle.png"/>
          <span style="display:block;">Log In</span>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="columns is-mobile mt-1">
      <div class="column">
        <%= link_to root_path, class: "items" do %>
          <img src="https://img.icons8.com/color/40/000000/airbnb.png"/>
          <span style="display:block;">Explore</span>
        <% end %>
      </div>
      <div class="column">
        <%= link_to trips_path, class: "items" do %>
          <img src="https://img.icons8.com/nolan/40/trekking.png"/>
          <span style="display:block;">Places</span>
        <% end %>
      </div>
      <div class="column">
        <%= link_to new_room_path, class: "items" do %>
          <img src="https://img.icons8.com/cotton/40/000000/home.png"/>
          <span style="display:block;">Host</span>
        <% end %>
      </div>
      <div class="column">
        <%= link_to edit_user_registration_path(@user), class: "items" do %>
          <img src="https://img.icons8.com/carbon-copy/40/000000/user-male-circle.png"/>
          <span style="display:block;">Profile</span>
        <% end %>
      </div>
      <div class="column">
        <%= link_to destroy_user_session_path, method: :delete, class: "items" do %>
          <img src="https://img.icons8.com/carbon-copy/40/000000/logout-rounded-down.png"/>
          <span style="display:block;">Logout</span>
        <% end %>
      </div>
    </div>
  <% end %>
</nav>
<%= javascript_pack_tag 'navbar' %>
<%= javascript_pack_tag 'bottom-navbar' %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://socialidiomas.com.br/main/wp-content/uploads/2016/09/banner-sao-paulo.jpg');">
  <div class="banner-content">
    <h1>There is Love in SP</h1>
    <p>Find the most romantic places in São Paulo </p>


<div class="search-bar">
    <form action="/offers" class="form-inline padded">
      <input type="text" class="form-control border-radius input-lg" placeholder="Av Paulista">
      <input type="text" name="checkin" class="form-control border-radius input-lg datepicker" placeholder="Checkin">
      <input type="text" name="checkout" class="form-control border-radius input-lg datepicker" placeholder="Checkout">

      <input type="submit" class="btn btn-danger btn-lg" value="Search">
    </form>
  </div>
  </div>
</div>

<h3 class = "text-center">Your <strong id="red-word">Lovespot</strong> in <strong id="red-word">São Paulo</strong>  </h3>

app/views/pages/search.html.erb
<div class="columns is-mobile searchcolumns">
  <div class="column is-two-thirds-widescreen is-three-fifths-desktop is-full-mobile">
    <div class="container is-fluid searchwrap mb-5">

       

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid" class="">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo1.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Offer a room", new_offer_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>